openapi: 3.0.1
info:
  title: My API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /department/list:
    get:
      summary: Get all departments
      operationId: getDepartments
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Department'
components:
  schemas:
    Department:
      type: object
      properties:
        id:
          type: string
        deptName:
          type: string
      required:
        - name